### ISSUE TITLE
Internal error thrown during session.beginTransaction()

### ISSUE THREAD

**Issue by louisiukas** [neo4j/neo4j-javascript-driver#118]
Version: `1.1.0-M01`

``` js
var neo4j = require('neo4j-driver').v1;
var neo4jDriver = neo4j.driver("bolt://neo4j", neo4j.auth.basic("neo4j", "...."), {
    encrypted: false
});
var session = neo4jDriver.session();
var tx = session.beginTransaction();
```

gives this error:

```
TypeError: this._onClose is not a function
    at Transaction._onError (/srv/app/node_modules/neo4j-driver/lib/v1/transaction.js:124:12)
    at _TransactionStreamObserver.onError (/srv/app/node_modules/neo4j-driver/lib/v1/transaction.js:150:18)
    at Connection._queueObserver (/srv/app/node_modules/neo4j-driver/lib/v1/internal/connector.js:466:20)
    at Connection.run (/srv/app/node_modules/neo4j-driver/lib/v1/internal/connector.js:391:12)
    at new Transaction (/srv/app/node_modules/neo4j-driver/lib/v1/transaction.js:61:16)
    at Session.beginTransaction (/srv/app/node_modules/neo4j-driver/lib/v1/session.js:119:14)
    at repl:1:18
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
```

It turns out it is an error during an error. The initial error is that the connection to the database failed (wrong server hostname).

In general, are you supposed to run a test query on the database to know whether the connection was successfull?

**Comment by zhenlineo** [comment]
No, with `1.1.0-M02`, this `var session = neo4jDriver.session();` is enough to ensure the connection with the server has established.
