### ISSUE TITLE
Exception: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by ahkimkoo** [neo4j/neo4j-javascript-driver#167]
'''
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1227:7)
    at TLSSocket.<anonymous> (/home/project/caimi/node_modules/neo4j-driver/lib/v1/internal/ch-node.js:175:65)
    at TLSSocket.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at TLSSocket.emit (events.js:179:7)
    at TLSSocket.<anonymous> (_tls_wrap.js:1078:16)
    at emitNone (events.js:80:13)
    at TLSSocket.emit (events.js:179:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
'''

run it forked process, throw exception.

**Comment by mhhf** [comment]
+1
same error on aws lambda because the HOME env is not set/ no home exists to create `.neo4j` dir
https://github.com/neo4j/neo4j-javascript-driver/blob/1.1/lib/v1/internal/ch-node.js#L201

@ahkimkoo try to set HOME=/tmp/

**Comment by zhenlineo** [comment]
Hi we have deprecated Trust_on_first_use in 1.1 releases and it will be replaced by trust_all_certs. So please prepare to move your code to the new driver to avoid this problem.

**Comment by yipcma** [comment]
yup, facing same problem on AWS lambda. I tried set key-value on lambda console, HOME, /tmp/, and it's working fine.

**Comment by zhenlineo** [comment]
Thanks a lot for providing the work around method and pls update your code to use new `trust_all_certs`.
Closing this issue as we already have a new milestone release with the new `trust_all_certs`.
