### ISSUE TITLE
V1.1.0 - causing module initialization error in AWS Lambda function

### ISSUE THREAD

**Issue by viz** [neo4j/neo4j-javascript-driver#200]
Deployed an unrelated (and trivial) change to one of our serverless/lambda projects last night and started getting:

`module initialization error: TypeError
at __webpack_require__ (/var/task/handler.js:20:30)
at Object.<anonymous> (/var/task/handler.js:85:27)
at __webpack_require__ (/var/task/handler.js:20:30)
at /var/task/handler.js:40:18
at Object.<anonymous> (/var/task/handler.js:43:10)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)`

After investigating for a a few hours discovered than npm had installed neo4j-driver v1.1.0 where we were previously using v1.0.4. In some of the functions we got enough trace info to indicate that this was happening when creating the driver:

`
const neoDriver = neo4j.v1.driver(process.env.NEO4J_BOLT_URL, neo4j.v1.auth.basic(process.env.NEO4J_USERNAME, process.env.NEO4J_PASSWORD), {
      encrypted: true,
      knownHosts: '/tmp/.neo4j/known_hosts',
    });
`

Forcing the version back to v1.0.4 resolved the issue.

I haven't had a chance to do much debugging on this yet as it took our prod services down and so was focused on fixing that. I wanted to post an issue to give you guys a heads up rather than wait until I did more debugging.

I'll try to work out what's going and and post an update here.

**Comment by bkapicka** [comment]
Replacing

```
 var neo4j = require('neo4j-driver').v1;
```
with 
```
 var neo4j = require('neo4j-driver');
```
appears to have resolved the issue.

**Comment by lutovich** [comment]
Hi @viz, @bkapicka.

You probably had `"neo4j-driver": "^1.0.4"` in the `package.json` which allowed npm to upgrade driver version to the most recent 1.x.x which currently is 1.1.0.

I do not think we've changed module name in 1.1.0, `require()` and driver initialization should remain the same. Is it possible that together with neo4j-driver smth else was updated and caused this problem? Could you maybe provide a small project where we can reproduce the problem?

Thanks!

**Comment by viz** [comment]
Yes, that's what we had in package.json - we've now locked it to 1.0.4 until we get this sorted out. We're also switching to yarn to make this sort of problem less likely.

Pretty sure that nothing else changed. I'll create a small project to verify.

**Comment by lutovich** [comment]
Hello @viz, did you have a chance to create a repro project?

**Comment by viz** [comment]
Haven't had a chance yet. I'll try to get it done this week :-)

**Comment by viz** [comment]
Finally came back to this and worked out what was going wrong.

I had assumed that I could:

```
import neo4j from 'neo4j-driver';
const driver = neo4j.v1.driver(...);
```
which generates an error:
```
module initialization error: TypeError
at Object.<anonymous> (/var/task/handler.js:107:25)
at __webpack_require__ (/var/task/handler.js:20:30)
at Object.<anonymous> (/var/task/handler.js:53:18)
at __webpack_require__ (/var/task/handler.js:20:30)
at Object.defineProperty.value (/var/task/handler.js:40:18)
at Object.<anonymous> (/var/task/handler.js:43:10)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
```

resolved the error by replacing with this:
```
const neoInst = require('neo4j-driver').v1;
const neoDriver = neoInst.driver(...);
```

My bad assuming that I can use `import` the same as `require`

**Comment by lutovich** [comment]
Hello @viz, nice, glad this problem is resolved!
