### ISSUE TITLE
Calling driver.close() after session.close() sometimes causes exception even if a callback is used

### ISSUE THREAD

**Issue by benstevens48** [neo4j/neo4j-javascript-driver#205]
Hi,
I think there is a bug whereby sometimes if you do
```js
session.close(() => {
driver.close();
});
```
then `driver.close()` throws an error.

I've looked at the code and think maybe this is the problem, in the driver.js file
```js
  _releaseConnection(connectionPromise) {
    return userDefinedCallback => {
      connectionPromise.then(conn => {
        // Queue up a 'reset', to ensure the next user gets a clean session to work with.
        conn.reset();
        conn.sync();
        // Return connection to the pool
        conn._release();
      }).catch(ignoredError => {
      });
      if (userDefinedCallback) {
        userDefinedCallback();
      }
    };
  }
```
Do you need to put `userDefinedCallback();` inside a then block after the catch?
Also, it would be useful if session.close() also returned a Promise so you could use session.close().then(...) as an alternative to a callback.

**Comment by lutovich** [comment]
Hi @benstevens48,

Thanks for reporting this problem. You are probably right, it looks strange that `if` is outside of the promise. However I was not able to reproduce the problem with a simple test like this:

```javascript
it('close driver while closing session', done => {
  driver = neo4j.driver('bolt://localhost', neo4j.auth.basic('neo4j', 'neo4j'));
  
  const session = driver.session();
    session.run('CREATE ()').then(() => {
      session.close(() => {
        driver.close();
        done();
    });
  });
});
```

Do you maybe have a test that shows how `driver.close()` fails?

**Comment by benstevens48** [comment]
Hi @lutovich,
I can only get the error to occur if the transaction also experiences an error. This code reproduces it in node 7.6.
```js
const neo4j = require('neo4j-driver').v1;

let neo4jUsername = "neo4j";
let neo4jPassword = "password";

async function main(){
    let driver = neo4j.driver('bolt://localhost', neo4j.auth.basic(neo4jUsername, neo4jPassword));
    let session = null;
    let tx = null;
    session = driver.session();
    try{
        tx = session.beginTransaction();
        await tx.run('INVALID QUERY');
        await tx.commit();
    }catch(error){
        console.log('An error occurred.');
        if(tx){
            try{
                await tx.rollback();
            }catch(ex){}
        }
    }
    session.close(() => {
        //setImmediate(() => {
            driver.close();
        //});
    });
}

main();
```
If you uncomment the setImmediate lines then the error goes away.

**Comment by lutovich** [comment]
@benstevens48 thanks a lot for the test! We will investigate.

**Update:** I can reproduce an error with your script:
```
$ node test.js
An error occurred.
/private/tmp/test/node_modules/neo4j-driver/lib/v1/internal/connector.js:349
            this._currentObserver.onCompleted(payload);
                                 ^

TypeError: Cannot read property 'onCompleted' of undefined
    at Connection._handleMessage (/private/tmp/test/node_modules/neo4j-driver/lib/v1/internal/connector.js:349:34)
    at Dechunker.Connection._dechunker.onmessage (/private/tmp/test/node_modules/neo4j-driver/lib/v1/internal/connector.js:294:12)
    at Dechunker._onHeader (/private/tmp/test/node_modules/neo4j-driver/lib/v1/internal/chunking.js:246:14)
    at Dechunker.AWAITING_CHUNK (/private/tmp/test/node_modules/neo4j-driver/lib/v1/internal/chunking.js:199:21)
    at Dechunker.write (/private/tmp/test/node_modules/neo4j-driver/lib/v1/internal/chunking.js:257:28)
    at NodeChannel.self._ch.onmessage (/private/tmp/test/node_modules/neo4j-driver/lib/v1/internal/connector.js:267:27)
    at TLSSocket.<anonymous> (/private/tmp/test/node_modules/neo4j-driver/lib/v1/internal/ch-node.js:302:16)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
```
