### ISSUE TITLE
I cant use multiple parallel request

### ISSUE THREAD

**Issue by ranlandau** [neo4j/neo4j-javascript-driver#259]
I'm trying to run Neo4J on NodeJS using parallel executions. I either get Socket Error, or EM Error, on ECONNETION RESET when running multiple.

"getaddrinfo EMFILE neo4j.dev.com:7687" or:

error in neo4jSession.run()Error: Connection was closed by server

and others.

Is there any common correct way to queue alot of parallel executions while no overloading the session?

Here is my code - which doesn't work.

```javascript
var neo4j = require('neo4j-driver').v1;
var Neo4jConfigurator = require("./config/Neo4jConfigurator.js").Neo4jConfigurator;
var Promise = require("bluebird");

var url = Neo4jConfigurator.instance().getDBURlIndexer();
var userName = Neo4jConfigurator.instance().getUserName();
var password = Neo4jConfigurator.instance().getPassword();
var requestPromise = require("request-promise");


var Neo4jSession = function()
{
    this.masterDriver = null;
    this.defaultDriver = this.setDefaultDriver();
    this.activeSessions = {};
}

Neo4jSession.prototype.getActiveSessions  = function(){
    return this.activeSessions;
}


Neo4jSession.prototype.getMasterDriver  = function(){
    return this.masterDriver;
}

Neo4jSession.prototype.setMasterDriver  = function(endPoint){
    var boltPort = Neo4jConfigurator.instance().getBoltPort();
    this.masterDriver = neo4j.driver("bolt://" + endPoint + ":" + boltPort ,  neo4j.auth.basic(userName, password),{encrypted:false, connectionPoolSize : 10});
}

Neo4jSession.prototype.setDefaultDriver  = function(){
  var url = Neo4jConfigurator.instance().getDBURlIndexer();
  var driver = neo4j.driver("bolt://" + url,  neo4j.auth.basic(userName, password),  {encrypted:false, connectionPoolSize : 10});
  return driver;
}

Neo4jSession.prototype.getDefaultDriver  = function(){
  return this.defaultDriver;
}

Neo4jSession.prototype.addDefaultSession  = function(){
  var driver =  this.getDefaultDriver();
  var session = driver.session();
  return session;
}

Neo4jSession.prototype.run  = function(cypherQuery){
  var session = this.addDefaultSession();
  this.addActiveSession(session);
  return session.run(cypherQuery);
}

Neo4jSession.prototype.runMasterSession  = function(cypherQuery){
  var driver = this.getMasterDriver();
  var masterSession = driver.session();
  this.addActiveSession(masterSession);
  return  masterSession.run(cypherQuery);
}

Neo4jSession.prototype.closeAllSessions  = function(){
  var neo4jSessionObj = this;
  Object.keys(this.getActiveSessions()).forEach(function(activeSessionId){
    neo4jSessionObj.getActiveSessions()[activeSessionId].close();
    delete neo4jSessionObj.getActiveSessions()[activeSessionId];
    //console.log('deleted session ' + activeSessionId);
  })
}

Neo4jSession.prototype.getActiveSessions  = function(){
  return this.activeSessions;
}

Neo4jSession.prototype.addActiveSession  = function(session){
  var neo4jSessionObj = this;
  var activeSessionsNumber = Object.keys(this.getActiveSessions()).length + 1;
  this.getActiveSessions()[activeSessionsNumber] = session;
  //console.log('added session ' + activeSessionsNumber);
}

Neo4jSession.prototype.initMaster  = function()
{
  var neo4jSessionObj = this;
  return new Promise(function(resolve, reject){
      Promise.each(Neo4jConfigurator.instance().getEndPoints(), function(endPoint){
          var masterRoute = Neo4jConfigurator.instance().getMasterRoute();
          var httpPort = Neo4jConfigurator.instance().getHttpPort();
          var boltPort = Neo4jConfigurator.instance().getBoltPort();
          options =  {    uri : 'http://' + endPoint + ":" + httpPort + masterRoute ,                                    
                          method: "GET",
                          headers: 
                          {
                              'Accept-Charset': 'utf-8'
                          }
                      }
          requestPromise(options)
          .then(function(body){
              try
              {
                  body = body.replace(/\0/g,' ');
                  json = JSON.parse(body);
                  if(json == true)
                  {             
                      neo4jSessionObj.setMasterDriver(endPoint);                                               
                      resolve(endPoint);             
                  }
              }
              catch(err)
              {
                reject(err)
              }
          })
          .catch(function(err){
            if(! err.error || err.error != 'false')
              reject(err);
          })  
      })
  })
}



module.exports = {
  Neo4jSession: Neo4jSession
}
```

**Comment by lutovich** [comment]
Hi @ranlandau,

Could you please share code that uses `Neo4jSession.prototype.run` and `Neo4jSession.prototype.runMasterSession` functions? It would be nice to see how sessions are closed after successful query execution.

I also edited your question to have a better JS code markup.

**Comment by rohitm** [comment]
I'm running into a very similar problem wherein `session.run()` poops out when I attempt to run more than 10 queries parallelly. Is there a suggested or standard method to queue multiple calls to `session.run()`?

This is my Implementation -
```
const driver = neo4j.driver(config.get('neo4j.host'),
  neo4j.auth.basic(config.get('neo4j.username'),
    config.get('neo4j.password')));

let session;

const runQuery = (query, params = {}) => new Promise(async (resolve, reject) => {
  session = driver.session();

  session.run(query, params).then((result) => {
    session.close();
    log.info(`Executed Query - "${query}"`);
    resolve(result);
  }).catch((error) => {
    session.close();
    reject(error);
  });
});
```
### Error
```
{ Neo4jError: The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. Transaction terminated, no more locks can be acquired. CommunityLockClient[7770]
    at new Neo4jError (/node_modules/neo4j-driver/lib/v1/error.js:76:132)
    at newError (/node_modules/neo4j-driver/lib/v1/error.js:66:10)
    at Connection._handleMessage (/node_modules/neo4j-driver/lib/v1/internal/connector.js:355:56)
    at Dechunker.Connection._dechunker.onmessage (/node_modules/neo4j-driver/lib/v1/internal/connector.js:286:12)
    at Dechunker._onHeader (/node_modules/neo4j-driver/lib/v1/internal/chunking.js:246:14)
    at Dechunker.AWAITING_CHUNK (/node_modules/neo4j-driver/lib/v1/internal/chunking.js:199:21)
    at Dechunker.write (/node_modules/neo4j-driver/lib/v1/internal/chunking.js:257:28)
    at NodeChannel.self._ch.onmessage (/node_modules/neo4j-driver/lib/v1/internal/connector.js:259:27)
    at TLSSocket.<anonymous> (/node_modules/neo4j-driver/lib/v1/internal/ch-node.js:308:16)
    at emitOne (events.js:96:13)
  code: 'Neo.TransientError.Transaction.LockClientStopped',
  name: 'Neo4jError' }
```

**Comment by lutovich** [comment]
Hi @rohitm,

Could you please change your code to not keep session in a variable outside of the promise? To something like this:

```javascript
const driver = neo4j.driver(config.get('neo4j.host'),
  neo4j.auth.basic(config.get('neo4j.username'),
    config.get('neo4j.password')));

const runQuery = (query, params = {}) => new Promise(async (resolve, reject) => {
  const session = driver.session(); // <<-- session is only visible inside the promise

  session.run(query, params).then((result) => {
    session.close();
    log.info(`Executed Query - "${query}"`);
    resolve(result);
  }).catch((error) => {
    session.close();
    reject(error);
  });
});
```

When session is closed driver sends a reset command to the database. This causes it to terminate ongoing transaction, if any. I suspect promises in your code could override each other's session variable and close the wrong one in `then()`/`catch()`. Which might cause transaction termination.

Hope this helps.

**Comment by rohitm** [comment]
@lutovich - This helps, thanks! I believe the session context being left outside made it common to all the parallel queries, and created a race condition.

**Comment by technige** [comment]
Closing due to inactivity. Please reopen if more information surfaces.
