### ISSUE TITLE
UncaughtException when running a Cypher statement

### ISSUE THREAD

**Issue by canibanoglu** [neo4j/neo4j-javascript-driver#26]
Hello again,

During development, we have come across a bug that brings node to its knees. Apart from listening to node's uncaughtException event, we couldn't find a way of handling this. `.catch()` and `onError` for promise-based approach and `subscribe()` approach, respectively, do not work.

I have tried this against M01 and M02 with corresponding installs from npm. This is the case in both of them. I have started looking into `packstream.js` but honestly I don't have the heart for it before I learn how bolt packs its data first. I will definitely look into it more and will let you know if I come across something but I expect you guys will pinpoint the problem right away.

The Cypher statement works correctly against the REST API, so I don't think anything is wrong with the Cypher itself. 

I have used the Movies dataset which I imported with `:play movies` on the included browser application. 

This is on a new node/express project with only `neo4j-driver` install with `npm install neo4j-driver`. As I said both `1.0.0-M02` and `1.0.0-M01` releases are affected. I haven't tried `3.0.0-M03` DB version yet, because, well, I don't know which branch to install from this repository to test against that. I would appreciate if you could help me there. 

On to the details!

``` js
var express = require('express');
var router = express.Router();
var n = require("neo4j-driver");

/* GET home page. */
router.get('/', function (req, res, next) {
  var driver = n.v1.driver("bolt://localhost:7687");
  var session = driver.session();
  session.run('match (k:`Person`) where id(k) = {idparam}\
    match p=(k)-[:ACTED_IN]-(m)\
    optional match p2= (k)-[:DIRECTED]-(c)\
  optional match p4= (m)-[:ACTED_IN]-()\
  optional match p5= (m)-[:DIRECTED]-() \
  return p,p2,p4,p5', {idparam: n.v1.int(71)}).subscribe({
    onNext     : function (record) {
      console.log(record);
    },
    onCompleted: function () {
      // Completed!
      session.close();
    },
    onError    : function (error) {
      console.log(error);
      res.send(error);
    }
  });
});

module.exports = router;
```

This is the only part that I have touched in the new project. This throws a `TypeError` with `Cannot read property 'start' of undefined`. The full stack is as follows:

``` js
  this.start = segments[0].start;
                          ^
TypeError: Cannot read property 'start' of undefined
    at new Path (/home/admins/Desktop/bolt/nodeTest/node_modules/neo4j-driver/lib/v1/graph-types.js:205:27)
    at path (/home/admins/Desktop/bolt/nodeTest/node_modules/neo4j-driver/lib/v1/internal/connector.js:172:12)
    at Unpacker.unpackStruct (/home/admins/Desktop/bolt/nodeTest/node_modules/neo4j-driver/lib/v1/internal/packstream.js:324:16)
    at Unpacker.unpack (/home/admins/Desktop/bolt/nodeTest/node_modules/neo4j-driver/lib/v1/internal/packstream.js:391:21)
    at Unpacker.unpackList (/home/admins/Desktop/bolt/nodeTest/node_modules/neo4j-driver/lib/v1/internal/packstream.js:304:25)
    at Unpacker.unpack (/home/admins/Desktop/bolt/nodeTest/node_modules/neo4j-driver/lib/v1/internal/packstream.js:387:21)
    at Unpacker.unpackStruct (/home/admins/Desktop/bolt/nodeTest/node_modules/neo4j-driver/lib/v1/internal/packstream.js:328:34)
    at Unpacker.unpack (/home/admins/Desktop/bolt/nodeTest/node_modules/neo4j-driver/lib/v1/internal/packstream.js:391:21)
    at Dechunker.Connection._dechunker.onmessage (/home/admins/Desktop/bolt/nodeTest/node_modules/neo4j-driver/lib/v1/internal/connector.js:240:42)
    at Dechunker._onHeader (/home/admins/Desktop/bolt/nodeTest/node_modules/neo4j-driver/lib/v1/internal/chunking.js:230:14)

Process finished with exit code 8
```

I hope this helps in recreating and fixing the issue. If there is any more information I can provide, please let me know. Anything I can look into myself, I'd be happy to if you could provide me with some pointers.

Kind regards,

Can

**Comment by canibanoglu** [comment]
I should have mentioned, 71 is the ID for Tom Hanks in my DB.

**Comment by jakewins** [comment]
Resolved by https://github.com/neo4j/neo4j-javascript-driver/commit/897fe5e93570baa7e55b2b3455305e54533d23b8
