### ISSUE TITLE
Session fails to close after transaction

### ISSUE THREAD

**Issue by andygreenegrass** [neo4j/neo4j-javascript-driver#261]
The following program hangs after attempting to close the session.

Using:
node v8.0.0
neo4j-driver v1.3.0

```js
#!/usr/bin/env node
'use strict';

const neo4j = require('neo4j-driver').v1;
const driver = neo4j.driver('bolt://localhost', neo4j.auth.basic('neo4j', 'test'));

async function main() {
  const session = driver.session();
  const tx = session.beginTransaction();
  try {
    const results = await tx.run(`
      CREATE (u:User {user})
    `, {
      user: {
        name: 'shouldntexist',
        pwHash: 'jibberish',
        email: 'idontwanttoseethis@no.com'
      }
    });
    console.log('QUERY RESULTS:');
    console.log(results);
    throw new Error('fail here');
  } catch(err) {
    console.error(err);
    console.log('ROLLBACK RESULTS:');
    console.log(await tx.rollback());
  } finally {
    console.log('CLOSE RESULTS:');
    console.log(await session.close());
  }
}

main();
```

Output:
```
QUERY RESULTS:
{ records: [],
  summary: 
   ResultSummary {
     statement: 
      { text: '\n      CREATE (u:User {user})\n    ',
        parameters: [Object] },
     statementType: 'w',
     counters: StatementStatistics { _stats: [Object] },
     updateStatistics: StatementStatistics { _stats: [Object] },
     plan: false,
     profile: false,
     notifications: [],
     server: ServerInfo { address: 'localhost:7687', version: 'Neo4j/3.2.0' },
     resultConsumedAfter: Integer { low: 0, high: 0 },
     resultAvailableAfter: undefined } }
Error: fail here
    at main (/Users/andy/projects/npm-repository-server/_testing/transactions.js:22:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
ROLLBACK RESULTS:
{ records: [],
  summary: 
   ResultSummary {
     statement: { text: 'ROLLBACK', parameters: {} },
     statementType: undefined,
     counters: StatementStatistics { _stats: [Object] },
     updateStatistics: StatementStatistics { _stats: [Object] },
     plan: false,
     profile: false,
     notifications: [],
     server: ServerInfo {},
     resultConsumedAfter: undefined,
     resultAvailableAfter: undefined } }
CLOSE RESULTS:
undefined
^C
```

**Comment by lutovich** [comment]
Hi @andygreenegrass,

Your program does manage to close session, right? I tried adding a `console.log` after `console.log(await session.close());` and it got printed. Open file descriptors and network connections can prevent node process from exiting. In your case driver created a single connection for that transaction but never closed it because driver itself has never been closed.

Adding `driver.close()` after `console.log(await session.close());` makes script exit cleanly. Driver keeps connections in a pool which is closed only when driver itself is closed.

Hope this helps.

**Comment by andygreenegrass** [comment]
I see. Thanks, that clears things up.
