### ISSUE TITLE
Windows 10 Error: Unknown scheme: bolt//

### ISSUE THREAD

**Issue by pentarex** [neo4j/neo4j-javascript-driver#281]
NodeJs v: 8.2.1
Neo4j v: 3.2.3
neo4-driver v: 1.4.0

When I try to run the project, I am getting an exception:
~~~sh
C:\Users\user\Documents\work\project\node_modules\neo4j-driver\lib\v1\index.js:173
    throw new Error('Unknown scheme: ' + scheme);
    ^

Error: Unknown scheme: bolt//
    at Object.driver (C:\Users\user\Documents\work\project\node_modules\neo4j-driver\lib\v1\index.js:173:11)
    at Object.<anonymous> (C:\Users\user\Documents\work\project\controllers\user\user.authentication.controller.js:11:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\Documents\work\project\controllers\user\user.controller.js:13:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Users\user\Documents\work\project\routes\user.routes.js:12:16)
    at module.exports (C:\Users\user\Documents\work\project\routes\api.js:8:29)
    at Object.<anonymous> (C:\Users\user\Documents\work\project\server.js:83:24)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)

Process finished with exit code 1
~~~

The project is running on linux without problems. Should I install something extra?

**Comment by lutovich** [comment]
Hi @pentarex,

Could you please post URI that you use to seed the driver?
I.e. URI used in `neo4j.driver("uri")` call.

**Comment by pentarex** [comment]
dev.js
~~~javascript
config.db = {};
config.db.protocol = 'bolt';
config.db.username = 'neo4j';
config.db.password = 'password';
config.db.domain   = 'localhost';
config.db.port     = '7474';

config.db.url = config.db.protocol + '//' + config.db.domain;
~~~

user.authentication.controller.js
~~~javascript
var driver = neo4j.driver(config.db.url, neo4j.auth.basic(config.db.username, config.db.password));
~~~

**Comment by lutovich** [comment]
How is `config.db.url` property defined? Is it somehow constructed from `config.db.protocol`, `config.db.domain` and `config.db.port`?

**Comment by pentarex** [comment]
sorry Ive updated my response but anyhow it is 
~~~javascript
config.db.url = config.db.protocol + '//' + config.db.domain;
~~~

**Comment by lutovich** [comment]
I think you are simply missing `:`. Error message says `Unknown scheme: bolt//`.
Could you please try:
`config.db.url = config.db.protocol + '://' + config.db.domain;`

**Comment by pentarex** [comment]
It is working now, what do you think is this going to make a problem under linux if the other colleague try to run it after I push the changes? :(

**Comment by lutovich** [comment]
I'd expect this code to never work because constructed URI is not a valid URI. It is supposed to have scheme, host and optional port defined and first two should be separated by `://`. Driver only accepts `bolt` and `bolt+routing` schemes. So valid URIs would be:

```
bolt://database.host.com
bolt://database.host.com:7687
bolt+routing://database.host.com
bolt+routing://database.host.com:7687
```

Hope this helps.

**Comment by pentarex** [comment]
Thanks a lot.
