### ISSUE TITLE
Bolt driver with Promises

### ISSUE THREAD

**Issue by hierozbosch** [neo4j/neo4j-javascript-driver#292]
Looking at the driver documentation, I'm seeing a callback example, but no promises:
```
var driver = neo4j.driver("bolt://localhost", neo4j.auth.basic("neo4j", "neo4j"));

// Register a callback to know if driver creation was successful:
driver.onCompleted = function () {
  // proceed with using the driver, it was successfully instantiated
};
```
Is there a way to promisify this driver method?  Bluebird promisify, for example?  Is this callback approach still the recommended practice?

Thanks,

**Comment by lutovich** [comment]
Hi @hierozbosch,

Thanks for raising this issue.
It is not mandatory to use driver's `onCompleted` and `onError` callbacks. If you need to verify connectivity I'd recommend running a dummy query like `RETURN 1`. Queries can return promises. Also these callbacks might not work in recent released like mentioned here: https://github.com/neo4j/neo4j-javascript-driver/issues/234.

Do you think this is an option for you?

**Comment by hierozbosch** [comment]
Thanks @lutovich,  your #234 explains part of what I'm seeing.  I'm moving onto a Docker swarm, where my website runs for a few minutes then dies.  The log was showing the driver occasionally instantiating--now I see why--it's when a _session.run_ connects.  My app runs fine locally, but fails on the swarm.  It's running a 1.4.0 driver against a vanilla Neo4j:3.2.1 container.  After a few minutes it stops getting a response from the server, then throws a EHOSTUNREACH error and croaks, as below:

```
16:32:29  HomeView submit query
16:32:41  HomeView res=[ok]
16:33:12  HomeView submit query
16:33:26  neo4j driver instantiated
16:33:27  HomeView res=[ok]
16:34:11  HomeView submit query
16:34:23  HomeView submit query
16:34:56  HomeView submit query
16:35:26  HomeView submit query
16:47:19  Error: read EHOSTUNREACH
16:47:19  at new Neo4jError (/home/geo/node_modules/neo4j-driver/lib/v1/error.js:76:132)
16:47:19  at newError (/home/geo/node_modules/neo4j-driver/lib/v1/error.js:66:10)
16:47:19  at NodeChannel._handleConnectionError (/home/geo/node_modules/neo4j-driver/lib/v1/internal/ch-node.js:328:41)
16:47:19  at emitOne (events.js:120:20)
16:47:19  at TLSSocket.emit (events.js:210:7)
16:47:19  at emitErrorNT (internal/streams/destroy.js:62:8)

```
Any ideas on that one?  Thanks

**Comment by lutovich** [comment]
@hierozbosch so is it fine for you to not use driver's `onCompleted` and `onError` callbacks?

I honestly have no idea why EHOSTUNREACH (No route to host) error happens in your environment. @benbc, @spacecowboy have you guys ever seen this problem?

**Comment by benbc** [comment]
@lutovich I don't think we've seen that problem. There are too many environmental variables for me to be able to guess at the reason for it.

**Comment by spacecowboy** [comment]
Yes, I've seen that issue at certain times.

@hierozbosch configuring Neo4j to run a cluster correctly in docker can be tricky.

I'm not entirely up to date on docker swarm but I presume that it uses a docker network.

- Are you using `bolt+routing://...` or plain old `bolt://...`? I'm pretty sure that `bolt+routing://...` will fail on a cluster running in docker without some very careful configuration.

**Comment by hierozbosch** [comment]
Thanks @lutovich, @benbc, @spacecowboy, I'm still working this issue--as I said, this app is launching neo4j in a container on a swarm (right now it's just a single--the cluster's coming next).  I realized I had forgotten to configure the file descriptor limit in my docker compose file used to launch the stack.  Actually this doesn't seem to be documented--I used an example from somebody else's compose file, so I'm not even sure it's right.  Anyway I set the limits via:
```
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
```
The site runs for a while but then dies after about a half hour.  The last log entry shows the driver calling the neo4j server but hanging.  I logged into the neo4j container and tried to get the status:

```
~ $ docker exec -it 0a8f2b06d5e9 /bin/sh
/var/lib/neo4j # bin/neo4j status
Neo4j is not running
/var/lib/neo4j # bin/cypher-shell
Connected to Neo4j 3.2.1 at bolt://localhost:7687.
Type :help for a list of available commands or :exit to exit the shell.
Note that Cypher queries must end with a semicolon.
neo4j> match (n) return count(n);
+----------+
| count(n) |
+----------+
| 74035    |
+----------+
1 row available after 511 ms, consumed after another 0 ms
```
So the `neo4j status` command says Neo4j is not running, but cypher-shell starts up and returns the correct number of nodes in the database.  And I can curl into port 7474 from the web server.  Also, the  /var/lib/neo4j/logs directory is empty.  The neo4j console is piped into AWS Cloudwatch, so I can see the startup commands:

```
19:54:16  Active database: graph.db
19:54:16  Directories in use:
19:54:16  home: /var/lib/neo4j
19:54:16  config: /var/lib/neo4j/conf
19:54:16  logs: /logs
19:54:16  plugins: /var/lib/neo4j/plugins
19:54:16  import: /var/lib/neo4j/import
19:54:16  data: /var/lib/neo4j/data
19:54:16  certificates: /var/lib/neo4j/certificates
19:54:16  run: /var/lib/neo4j/run
19:54:16  Starting Neo4j.
19:54:19  2017-09-28 19:54:19.276+0000 WARN Unknown config option: causal_clustering.discovery_listen_address
19:54:19  2017-09-28 19:54:19.277+0000 WARN Unknown config option: causal_clustering.raft_advertised_address
19:54:19  2017-09-28 19:54:19.277+0000 WARN Unknown config option: causal_clustering.raft_listen_address
19:54:19  2017-09-28 19:54:19.277+0000 WARN Unknown config option: ha.host.coordination
19:54:19  2017-09-28 19:54:19.278+0000 WARN Unknown config option: causal_clustering.transaction_advertised_address
19:54:19  2017-09-28 19:54:19.279+0000 WARN Unknown config option: causal_clustering.discovery_advertised_address
19:54:19  2017-09-28 19:54:19.279+0000 WARN Unknown config option: ha.host.data
19:54:19  2017-09-28 19:54:19.279+0000 WARN Unknown config option: causal_clustering.transaction_listen_address
19:54:19  2017-09-28 19:54:19.405+0000 INFO ======== Neo4j 3.2.1 ========
19:54:19  2017-09-28 19:54:19.511+0000 INFO No SSL certificate found, generating a self-signed certificate..
19:54:22  2017-09-28 19:54:22.182+0000 INFO Starting...
19:54:25  2017-09-28 19:54:25.175+0000 INFO Bolt enabled on 0.0.0.0:7687.
19:54:37  2017-09-28 19:54:37.839+0000 INFO Started.
19:54:42  2017-09-28 19:54:42.754+0000 INFO Remote interface available at http://localhost:7474/
```
No clues there.  Is there any way to see what the server is doing?  Or the driver?
Thanks!


Are there other configuration settings that might choke it off?

**Comment by spacecowboy** [comment]
`neo4j status` is only valid if neo4j is running in the background using `neo4j start`. In docker it runs in the foreground (`neo4j console`) so the logs to the right place.

As you can see at line 5 in the console log you posted, logs will be posted to `/logs` (this might be a symlink but just trust the output here) have a look there and see if you can find the `debug.log`.

Could you explain what you mean @hierozbosch  by 

>The site runs for a while but then dies after about a half hour.

clearly you are able to start a shell in the container and execute a query via cypher-shell so by definition the database can't be dead. Are you referring to the neo4j-browser? Because the browser has on occasion been provoked into dying (but neo4j itself kept on running fine).

**Comment by hierozbosch** [comment]
Thanks @spacecowboy, I've been able to review the debug.log, showing the 64 times I restarted the neo4j server since 9/11.  There are no errors reported, and the server has never crashed.  It's running on an m3.medium (3.75G), configured with OS 1.7G, heap 2G, pagecache 100k (small dataset).  When I exec into the server container and run queries with cypher-shell, the response times are 1-2ms--absolutely fine.

The client app is what I referred to as "the site"--it's a webserver.  This is a node app using neo4j-driver for JS (v1.4.0).  Driver calls are made using the promises format (not streaming).  The app runs fine on the dev box using localhost:7867 to connect to neo4j.  Runs all day.

But on the docker swarm, it tanks after running a while, maybe 20 or 30 minutes.  When the swarm services are deployed, the website pops right up.  But pages with neo4j queries load a lot slower.  You can reload the same page repeatedly--the query will run 15 times in a row.  Then, on the 16th (or whatever), the log shows the query being made, but no response comes back--it just hangs like it doesn't connect.  It appears to lock up and the swarm manager restarts the service.

So I'm back to looking at the client side today--the server seems like it might be ok.  I can bump it up to an m3.large, but not sure that's the issue.

Appreciate your help!  Thanks.

**Comment by spacecowboy** [comment]
More memory will not fix this issue so you can leave the instance as is.

Does docker swarm imply some kind of load balancing in front of Neo4j? The drivers re-use sessions to communicate with Neo4j and they do *not* check if those sessions have been closed. A load balancer or proxy server might very well terminate idle sessions which could make your client die after a while.

**Comment by hierozbosch** [comment]
The swarm manager DOES use a load balancer, but I think it's only on the
ingress network, balancing inbound requests.  The neo4j server is linked
to the webservers on a "backend" overlay network.  But to be honest, I
don't really know how the swarm managers handle these overlay networks,
so it's entirely possible that a connection could get terminated.  Helps
to know that the driver is not checking the session, because it looks
like it could be hanging on a bad connection. 

I'll try creating new sessions on a call-by-call basis (then closing
them after I get results).  I'll just do that on the home page first and
see what happens.  I'll let you know. 

Thanks, I really appreciate your help on this. 

---

Matthew Hodges
GeoCertify, LLC
e: hodges@geocertify.com

On 2017-09-29 11:37, Jonas Kalderstam wrote:

> More memory will not fix this issue so you can leave the instance as is. 
> 
> Does docker swarm imply some kind of load balancing in front of Neo4j? The drivers re-use sessions to communicate with Neo4j and they do _not_ check if those sessions have been closed. A load balancer or proxy server might very well terminate idle sessions which could make your client die after a while. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/neo4j/neo4j-javascript-driver/issues/292#issuecomment-333160700
[2]

**Comment by hierozbosch** [comment]
FYI @spacecowboy:  As you suggested looking for idle sessions getting terminated, I found this on Docker:   "Idle connections over overlay network ends up in a broken state after 15 minutes #31208"  [https://github.com/moby/moby/issues/31208](url)

**Comment by spacecowboy** [comment]
@hierozbosch yup, terminating Idle connections is really common. Sounds like it could be the reason. I gave it a cursory glance but could not find any configuration options available for Swarm in this regard. Other load balancers like HaProxy allows you to configure the idle-timeout.

Making sure you don't have long running sessions should work - but sometimes they are actually needed. Let us know how you get on or if you find some options for Swarm which are relevant for a solution.

**Comment by hierozbosch** [comment]
@spacecowboy, I'm still looking into setting the connection timeouts on the docker overlay network.  However, extending the timeout would only be a partial solution since it would reduce but not eliminate the connections expiring.  I can possibly leave the connections open indefinitely, but over time that might lead to other problems.  In any case, I, too, have not yet found a way to configure that timeout on the swarm.

So I'm continuing to work with the neo4j-driver.  My attempt to call session() with each query (mentioned earlier) did not work.  As I looked into it, I saw the driver is managing a pool of sessions.  Calling the session() method just returns one of these out of the pool.  So apparently the session() call could be returning a terminated connection.

So now I've stepped up to the driver itself.  I created an object that holds and manages my instantiated driver.  Among other things, it contains its own run() method, so all my neo4j.run() calls are now getting routed through this object.  Basically, before passing the query to the driver's run() method, this one checks to see if the driver and its connections are more than 10 minutes old.  If so, it will check to see if there are any pending queries still outstanding.  If so, it will just use the existing driver. 
 But if not, then it will close the current driver and create a new one.  So far this seems to be working.

**Comment by benbc** [comment]
@hierozbosch You can set `connection.liveliness.check.timeout` in your driver config so that it checks the connections before using them. That timeout should be less than the timeouts of any infrastructure in front of your Neo4j server.

**Comment by lutovich** [comment]
@benbc we only have such setting for java driver right now.
@hierozbosch could you maybe try 1.5.0-rc1 driver that can be installed with `npm install --save neo4j-driver@next`? It has a new config setting called `maxConnectionLifetime` which sets maximum connection lifetime for every pooled connection. Driver with this setting set can be created like this:

```javascript
const neo4j = require('neo4j-driver').v1;
const config = {maxConnectionLifetime: 10 * 60 * 1000}; // 10 minutes
const driver = neo4j.driver('bolt://localhost', neo4j.auth.basic('neo4j', 'password'), config);
```

Pooled connection older than this timeout will be dropped during acquisition and will not be used to send queries.

Hope this helps.

**Comment by lutovich** [comment]
Closing because of inactivity. Hope the problem is resolved. Callbacks `Driver.onCompleted` and `Driver.onError` should not be used. We might come up with a better API in the next major driver release.
