### ISSUE TITLE
got Neo4jError: Connection was closed by server when merge relationship between nodes

### ISSUE THREAD

**Issue by liz282907** [neo4j/neo4j-javascript-driver#309]
when i use the neo4j-driver to relate the created nodes, i always get the following errors:
and i tried to restart the neo4j and run the code, the same as before
> -------final err { Neo4jError: Connection was closed by server
>     at new Neo4jError (/Users/luchen/Documents/研二/毕设相关/graduation/hacking-team-analysis/node_modules/_neo4j-driver@1.5.0@neo4j-driver/lib/v1/error.js:76:132)
>     at newError (/Users/luchen/Documents/研二/毕设相关/graduation/hacking-team-analysis/node_modules/_neo4j-driver@1.5.0@neo4j-driver/lib/v1/error.js:66:10)
>     at NodeChannel._handleConnectionTerminated (/Users/luchen/Documents/研二/毕设相关/graduation/hacking-team-analysis/node_modules/_neo4j-driver@1.5.0@neo4j-driver/lib/v1/internal/ch-node.js:338:41)
>     at emitNone (events.js:91:20)
>     at TLSSocket.emit (events.js:186:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ServiceUnavailable', name: 'Neo4jError' }

the functions are as follows, i wanna know whether is my data too large?(the relations are only 50000+). or any other mistakes i made?

`
   
    function getCypherArr(pairMap,nameSet){
          nameSet = [...new Set(nameSet)]
           const nodesCypher = nameSet.map(name=>{
              const transformed = helper.preprocessName(name);
              return `create (${transformed}:Person {name:'${name}'})`
    });

    const cypherFactory = (pairKey,pairVal)=> {
        const [fromPerson, toPerson] = pairKey.split('||');

        let transedFrom = helper.preprocessName(fromPerson),
            transedTo = helper.preprocessName(toPerson);

        const {to, cc, bcc} = pairVal;

        // ---------------cypher statements!----------------
        const prefix = [`MATCH (${transedFrom}:Person{name: '${fromPerson}'})`,
            `MATCH (${transedTo}:Person{name: '${toPerson}'})`,
            `with ${transedFrom},${transedTo}`].join('\n');

        const onepairCypher = ['to','bcc','cc'].reduce((prev,type)=>{
            const cur = pairVal[type].map(emailId=>  `MERGE (${transedFrom})-[:${type.toUpperCase()}{emailId: ${emailId}}]->(${transedTo})`);
            return prev.concat(cur);
        },[]).join('\n');

        return prefix + '\n'+ onepairCypher+'\n';
    }
    const edgesCypher = [];
    for(let [key,value] of Object.entries(pairMap)){
        const cypher = cypherFactory(key,value);
        edgesCypher.push(cypher);
    }
    return  {
        nodesCypher,
        edgesCypher
    };

}
// async library to do the jobs parallelly.
```
function parallelCreate(cypherArr,bulkLen,limit = 10) {
    const executeCypher =  (cypher,curNum)=> {
        var session = driver.session();
        return (callback)=>{
            session
                .run(cypher)
                .then(result => {
                    console.log('----------done',curNum)
                    callback(null, 'done cypher')
                    session.close();
                })
                .catch(error => {
                    session.close();
                    callback(error)
                    // throw error;
                });
        }
    }
```
    const groupedArr = [];
    for(let i=0;i<Math.ceil(cypherArr.length/bulkLen);i++){
        const cypherBulks = cypherArr.slice(i*bulkLen,(i+1)*bulkLen);
        const cypher = cypherBulks.join('\n');

        groupedArr.push(executeCypher(cypher,i));
    }

    const promise = new Promise((res,rej)=>{
        async.parallelLimit(groupedArr,limit,(err, results)=>{
            if(err) {
                return rej(err)
            }
            res(results);
        })
    })
    return promise

}

the called function:
     ```
 const cyphers =  getCypherArr(JSON.parse(mapData),JSON.parse(nameSet));
        parallelCreate(cyphers.edgesCypher.slice(0,1000),bulkLen).then((results)=>{
            console.log('------final done')
        }).catch(err=>{
            console.log('-------final err',err)
        });
```

`

**Comment by lutovich** [comment]
Hi @liz282907,

Could you please check `neo4j.log` and `debug.log` database logs for errors?
Code looks correct to me.

**Comment by liz282907** [comment]
i'm sorry to see the reply till now. i tried another approach by using the cql file...

**Comment by lutovich** [comment]
@liz282907 does it work fine for you right now?

**Comment by lutovich** [comment]
Closing because of inactivity. Hope everything works as expected now. Please update the issue if the problem still exists.
