### ISSUE TITLE
RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range

### ISSUE THREAD

**Issue by JavascriptMick** [neo4j/neo4j-javascript-driver#327]
Getting an intermittent crash of my Node application.  Using the neo4j-driver

driver version....
    "neo4j-driver": {
      "version": "1.5.1",
      "resolved": "https://registry.npmjs.org/neo4j-driver/-/neo4j-driver-1.5.1.tgz",
      "integrity": "sha1-VGedxGf96Vf7fI8FU81fjMmOBTE=",
      "requires": {
        "babel-runtime": "6.26.0"
      }
    },

node --version
v9.2.0

neo4j --version
neo4j 3.3.0

Error occurs when my express app issues a cypher statement against local instance.

Exception in my app logs...
[2] RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
[2]     at checkOffset (buffer.js:1019:11)
[2]     at Buffer.readUInt8 (buffer.js:1059:5)
[2]     at NodeBuffer.getUInt8 (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/buf.js:713:27)
[2]     at NodeBuffer.readUInt8 (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/buf.js:245:19)
[2]     at Unpacker.unpack (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/packstream.js:406:27)
[2]     at Unpacker._unpackListWithSize (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/packstream.js:521:25)
[2]     at Unpacker._unpackList (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/packstream.js:505:21)
[2]     at Unpacker.unpack (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/packstream.js:429:23)
[2]     at Unpacker._unpackStructWithSize (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/packstream.js:595:34)
[2]     at Unpacker._unpackStruct (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/packstream.js:576:21)

**Comment by lutovich** [comment]
Hi @JavascriptMick,

Do you know which query causes this error? Are there any exceptions logged on the database side during the same timeframe? Seeing `debug.log` and `neo4j.log` from the database would be valuable.

**Comment by JavascriptMick** [comment]
closing, upgraded to version": "1.5.3" and can't reproduce.
