### ISSUE TITLE
RangeError: Index out of range

### ISSUE THREAD

**Issue by panthershark** [neo4j/neo4j-javascript-driver#339]
With neo4j 3.3.3 and the latest driver, we have code that previously worked but has now stopped working. It previously worked with neo4j 3.2.x. I've attached code that causes the issue. It also causes the neo4j server to stop responding for a short time (my guess is this has to do with a hanging transaction or something).

To get this error, the query must match some nodes, run FOREACH, then attempt to return with EXTRACT.

### Error Message

```
buffer.js:972
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:972:11)
    at Buffer.readUInt8 (buffer.js:1010:5)
    at NodeBuffer.getUInt8 (/path-to-folder/neo33bug/node_modules/neo4j-driver/lib/v1/internal/buf.js:713:27)
    at NodeBuffer.readUInt8 (/path-to-folder/neo33bug/node_modules/neo4j-driver/lib/v1/internal/buf.js:245:19)
    at Unpacker.unpack (/path-to-folder/neo33bug/node_modules/neo4j-driver/lib/v1/internal/packstream.js:406:27)
    at Unpacker._unpackListWithSize (/path-to-folder/neo33bug/node_modules/neo4j-driver/lib/v1/internal/packstream.js:521:25)
    at Unpacker._unpackList (/path-to-folder/neo33bug/node_modules/neo4j-driver/lib/v1/internal/packstream.js:505:21)
    at Unpacker.unpack (/path-to-folder/neo33bug/node_modules/neo4j-driver/lib/v1/internal/packstream.js:429:23)
    at Unpacker._unpackListWithSize (/path-to-folder/neo33bug/node_modules/neo4j-driver/lib/v1/internal/packstream.js:521:25)
    at Unpacker._unpackList (/path-to-folder/neo33bug/node_modules/neo4j-driver/lib/v1/internal/packstream.js:505:21)
```

### Reproduction

1. Start a clean neo4j 3.3.3 instance
2. Put the code below into a file
3. install neo4j driver and run this code

```
const neo4j = require('neo4j-driver').v1;
const auth = neo4j.auth.basic('neo4j', 'dogs');
const db = neo4j.driver('bolt://localhost', auth);

const d1 = {
  name: 'spike',
  breed: 'bulldog'
};

const d2 = {
  name: 'spot',
  breed: 'chihuahua'
};

const session = db.session();

session
  .run(`MATCH (n) DETACH DELETE n`, {
    d1,
    d2
  })
  .then(() =>
    session.run(`CREATE (d1:dog {d1}), (d2:dog {d2})`, {
      d1,
      d2
    })
  )
  .then(() =>
    session.run(
      `MATCH (d:dog)  
     WITH COLLECT(d) as dogs
     FOREACH(d in dogs |
      SET d.name = d.name
    )
     RETURN EXTRACT(d in dogs | d{ .name, .breed }) as dogs
    `,
      {}
    )
  )
  .then((res) => {
    session.close();
    console.log(res);
    process.exit(0);
  })
  .catch((e) => {
    session.close();
    console.log(e);
    process.exit(1);
  });
```

**Comment by lutovich** [comment]
Closing this issue, turned out to be a Cypher problem. See https://github.com/neo4j/neo4j/issues/11309 for more details.

@tommymessbauer thanks again for the reliable repro!

**Comment by panthershark** [comment]
no problem.  Thank you for the quick resolution.  We'll upgrade to 3.3.x when this goes live.  :)
