### ISSUE TITLE
Cannot read property 'length' of null (record.js)

### ISSUE THREAD

**Issue by JavascriptMick** [neo4j/neo4j-javascript-driver#369]
version:
neo4j-driver@1.5.3

context:
several page requests initiating fetch queries on the db

I noticed that there is no null check on the *keys* parameter to the Record constructor here...
https://github.com/neo4j/neo4j-javascript-driver/blob/1.7/src/v1/record.js

[2] /Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/record.js:81
[2]     this.length = keys.length;
[2]                        ^
[2] TypeError: Cannot read property 'length' of null
[2]     at new Record (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/record.js:81:24)
[2]     at StreamObserver.onNext (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/stream-observer.js:69:20)
[2]     at Connection._handleMessage (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/connector.js:345:33)
[2]     at Dechunker.Connection._dechunker.onmessage (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/connector.js:289:12)
[2]     at Dechunker._onHeader (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/chunking.js:246:14)
[2]     at Dechunker.AWAITING_CHUNK (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/chunking.js:199:21)
[2]     at Dechunker.write (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/chunking.js:257:28)
[2]     at NodeChannel.self._ch.onmessage (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/connector.js:262:27)
[2]     at TLSSocket.<anonymous> (/Users/michael/Workspace/learntree.org/node_modules/neo4j-driver/lib/v1/internal/ch-node.js:308:16)
[2]     at TLSSocket.emit (events.js:159:13)
[2] [nodemon] app crashed - waiting for file changes before starting...

**Comment by lutovich** [comment]
Hi @JavascriptMick,

It is quite strange that `keys` parameter is null. This parameter represents an array of keys in every returned record. It should correspond to the things being returned from a Cypher query. Query `RETURN 'Bob' AS name, 20 AS age, 42 AS answer` keys should be an array `['name', 'age', 'answer']`.

Could you please specify which neo4j version are you using and provide an example of the query that causes such error?

**Comment by JavascriptMick** [comment]
Hi @lutovich  thanks for the reply, I have included some details about version and queries below, maybe an issue with using the OPTIONAL MATCH?

Note also that these queries don't consistently fail, in fact the pages load fine normally, there is just this one instance of a crash.

The only other thing I noticed that may be a contributing factor is I think my pages are loading the same data a few times so I might be stressing out the DB a little with a burst of queries.  Only running on a macbook pro.

version:
neo4j 3.3.0

Query 1:
MATCH (n:Learnable{tag:$tag}) RETURN n

Query 2:
MATCH (learnable:Learnable{tag:$tag})<-[learnableResource:TEACHES]-(resource:Resource)
WHERE NOT resource:Pending
OPTIONAL MATCH (resource)-[:TAUGHT_BY]->(teacher:Person)
OPTIONAL MATCH (resource)-[:HOSTED_BY]->(host:Organisation)
RETURN learnableResource, resource, teacher, host

**Comment by lutovich** [comment]
@JavascriptMick queries look good to me. Could you please share database logs (`neo4j.log` and `debug.log`)?

**Comment by JavascriptMick** [comment]
error occurred around 2018-05-07

neo4j.log
2018-05-02 13:28:29.794+0000 INFO  ======== Neo4j 3.3.0 ========
2018-05-02 13:28:29.841+0000 INFO  Starting...
2018-05-02 13:28:31.239+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-05-02 13:28:35.682+0000 INFO  Started.
2018-05-02 13:28:36.904+0000 INFO  Remote interface available at http://localhost:7474/
2018-05-09 22:29:28.812+0000 INFO  Neo4j Server shutdown initiated by request
2018-05-09 22:29:28.903+0000 INFO  Stopping...
2018-05-09 22:29:29.011+0000 INFO  Stopped.

debug.log
2018-05-02 13:28:33.120+0000 INFO [o.n.k.i.DiagnosticsManager] --- STARTED diagnostics for NEO_STORE_RECORDS END ---
2018-05-02 13:28:33.121+0000 INFO [o.n.k.i.DiagnosticsManager] --- STARTED diagnostics for TRANSACTION_RANGE START ---
2018-05-02 13:28:33.121+0000 INFO [o.n.k.i.DiagnosticsManager] Transaction log:
2018-05-02 13:28:33.122+0000 INFO [o.n.k.i.DiagnosticsManager] Oldest transaction 2 found in log with version 0
2018-05-02 13:28:33.122+0000 INFO [o.n.k.i.DiagnosticsManager] --- STARTED diagnostics for TRANSACTION_RANGE END ---
2018-05-02 13:28:33.128+0000 INFO [o.n.k.i.DiagnosticsManager] --- STARTED diagnostics for KernelDiagnostics:StoreFiles START ---
2018-05-02 13:28:33.129+0000 INFO [o.n.k.i.DiagnosticsManager] Disk space on partition (Total / Free / Free %): 499898105856 / 213604081664 / 42
2018-05-02 13:28:33.129+0000 INFO [o.n.k.i.DiagnosticsManager] Storage files: (filename : modification date - size)
2018-05-02 13:28:33.130+0000 INFO [o.n.k.i.DiagnosticsManager]   index:
2018-05-02 13:28:33.131+0000 INFO [o.n.k.i.DiagnosticsManager]   - Total: 2017-11-28T22:13:24+1100 - 0.00 B
2018-05-02 13:28:33.132+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore: 2018-04-25T13:56:24+1000 - 8.00 kB
2018-05-02 13:28:33.132+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.counts.db.a: 2018-04-25T13:56:24+1000 - 1.81 kB
2018-05-02 13:28:33.132+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.counts.db.b: 2018-04-05T20:09:57+1000 - 1.81 kB
2018-05-02 13:28:33.133+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.id: 2018-05-02T23:28:31+1000 - 9.00 B
2018-05-02 13:28:33.133+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.labelscanstore.db: 2018-05-02T23:28:32+1000 - 48.00 kB
2018-05-02 13:28:33.133+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.labeltokenstore.db: 2018-03-03T22:58:09+1100 - 8.00 kB
2018-05-02 13:28:33.133+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.labeltokenstore.db.id: 2018-05-02T23:28:31+1000 - 9.00 B
2018-05-02 13:28:33.134+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.labeltokenstore.db.names: 2018-03-03T22:58:09+1100 - 8.00 kB
2018-05-02 13:28:33.134+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.labeltokenstore.db.names.id: 2018-05-02T23:28:31+1000 - 9.00 B
2018-05-02 13:28:33.134+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.nodestore.db: 2018-04-25T13:56:24+1000 - 8.00 kB
2018-05-02 13:28:33.135+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.nodestore.db.id: 2018-05-02T23:28:31+1000 - 1.01 kB
2018-05-02 13:28:33.135+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.nodestore.db.labels: 2017-11-28T22:13:24+1100 - 8.00 kB
2018-05-02 13:28:33.135+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.nodestore.db.labels.id: 2018-05-02T23:28:31+1000 - 9.00 B
2018-05-02 13:28:33.136+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.propertystore.db: 2018-04-25T13:56:24+1000 - 23.90 kB
2018-05-02 13:28:33.136+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.propertystore.db.arrays: 2017-12-19T19:07:45+1100 - 24.00 kB
2018-05-02 13:28:33.136+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.propertystore.db.arrays.id: 2018-05-02T23:28:31+1000 - 9.00 B
2018-05-02 13:28:33.136+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.propertystore.db.id: 2018-05-02T23:28:31+1000 - 545.00 B
2018-05-02 13:28:33.137+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.propertystore.db.index: 2018-02-09T21:31:15+1100 - 8.00 kB
2018-05-02 13:28:33.137+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.propertystore.db.index.id: 2018-05-02T23:28:31+1000 - 9.00 B
2018-05-02 13:28:33.137+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.propertystore.db.index.keys: 2018-02-09T21:31:15+1100 - 8.00 kB
2018-05-02 13:28:33.138+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.propertystore.db.index.keys.id: 2018-05-02T23:28:31+1000 - 9.00 B
2018-05-02 13:28:33.138+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.propertystore.db.strings: 2018-04-25T13:56:24+1000 - 24.00 kB
2018-05-02 13:28:33.138+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.propertystore.db.strings.id: 2018-05-02T23:28:31+1000 - 353.00 B
2018-05-02 13:28:33.139+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.relationshipgroupstore.db: 2017-11-28T22:13:24+1100 - 8.00 kB
2018-05-02 13:28:33.139+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.relationshipgroupstore.db.id: 2018-05-02T23:28:31+1000 - 9.00 B
2018-05-02 13:28:33.139+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.relationshipstore.db: 2018-04-25T13:56:24+1000 - 23.91 kB
2018-05-02 13:28:33.140+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.relationshipstore.db.id: 2018-05-02T23:28:31+1000 - 793.00 B
2018-05-02 13:28:33.140+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.relationshiptypestore.db: 2018-03-03T22:58:09+1100 - 8.00 kB
2018-05-02 13:28:33.140+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.relationshiptypestore.db.id: 2018-05-02T23:28:31+1000 - 9.00 B
2018-05-02 13:28:33.141+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.relationshiptypestore.db.names: 2018-03-03T22:58:09+1100 - 8.00 kB
2018-05-02 13:28:33.141+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.relationshiptypestore.db.names.id: 2018-05-02T23:28:31+1000 - 9.00 B
2018-05-02 13:28:33.141+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.schemastore.db: 2018-01-23T08:24:51+1100 - 8.00 kB
2018-05-02 13:28:33.141+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.schemastore.db.id: 2018-05-02T23:28:31+1000 - 129.00 B
2018-05-02 13:28:33.142+0000 INFO [o.n.k.i.DiagnosticsManager]   neostore.transaction.db.0: 2018-05-02T23:14:29+1000 - 538.15 kB
2018-05-02 13:28:33.142+0000 INFO [o.n.k.i.DiagnosticsManager]   schema:
2018-05-02 13:28:33.142+0000 INFO [o.n.k.i.DiagnosticsManager]     index:
2018-05-02 13:28:33.142+0000 INFO [o.n.k.i.DiagnosticsManager]       lucene_native-1.0:
2018-05-02 13:28:33.142+0000 INFO [o.n.k.i.DiagnosticsManager]         43:
2018-05-02 13:28:33.143+0000 INFO [o.n.k.i.DiagnosticsManager]           lucene-1.0:
2018-05-02 13:28:33.143+0000 INFO [o.n.k.i.DiagnosticsManager]             1:
2018-05-02 13:28:33.143+0000 INFO [o.n.k.i.DiagnosticsManager]               _7.cfe: 2018-03-05T10:17:08+1100 - 305.00 B
2018-05-02 13:28:33.143+0000 INFO [o.n.k.i.DiagnosticsManager]               _7.cfs: 2018-03-05T10:17:08+1100 - 1.47 kB
2018-05-02 13:28:33.144+0000 INFO [o.n.k.i.DiagnosticsManager]               _7.si: 2018-03-05T10:17:08+1100 - 401.00 B
2018-05-02 13:28:33.144+0000 INFO [o.n.k.i.DiagnosticsManager]               segments_1l: 2018-05-02T23:14:29+1000 - 151.00 B
2018-05-02 13:28:33.144+0000 INFO [o.n.k.i.DiagnosticsManager]               write.lock: 2018-01-23T08:14:18+1100 - 0.00 B
2018-05-02 13:28:33.144+0000 INFO [o.n.k.i.DiagnosticsManager]             - Total: 2018-05-02T23:14:29+1000 - 2.31 kB
2018-05-02 13:28:33.145+0000 INFO [o.n.k.i.DiagnosticsManager]             failure-message: 2018-01-23T08:14:18+1100 - 16.00 kB
2018-05-02 13:28:33.145+0000 INFO [o.n.k.i.DiagnosticsManager]           - Total: 2018-01-23T08:14:18+1100 - 18.31 kB
2018-05-02 13:28:33.145+0000 INFO [o.n.k.i.DiagnosticsManager]           native-1.0:
2018-05-02 13:28:33.145+0000 INFO [o.n.k.i.DiagnosticsManager]             index-43: 2018-05-02T23:28:32+1000 - 40.00 kB
2018-05-02 13:28:33.145+0000 INFO [o.n.k.i.DiagnosticsManager]           - Total: 2018-01-23T08:14:18+1100 - 40.00 kB
2018-05-02 13:28:33.146+0000 INFO [o.n.k.i.DiagnosticsManager]         - Total: 2018-01-23T08:14:18+1100 - 58.31 kB
2018-05-02 13:28:33.146+0000 INFO [o.n.k.i.DiagnosticsManager]         50:
2018-05-02 13:28:33.146+0000 INFO [o.n.k.i.DiagnosticsManager]           lucene-1.0:
2018-05-02 13:28:33.146+0000 INFO [o.n.k.i.DiagnosticsManager]             1:
2018-05-02 13:28:33.146+0000 INFO [o.n.k.i.DiagnosticsManager]               _3.cfe: 2018-03-05T10:17:08+1100 - 305.00 B
2018-05-02 13:28:33.147+0000 INFO [o.n.k.i.DiagnosticsManager]               _3.cfs: 2018-03-05T10:17:08+1100 - 1.20 kB
2018-05-02 13:28:33.147+0000 INFO [o.n.k.i.DiagnosticsManager]               _3.si: 2018-03-05T10:17:08+1100 - 364.00 B
2018-05-02 13:28:33.147+0000 INFO [o.n.k.i.DiagnosticsManager]               segments_1l: 2018-05-02T23:14:29+1000 - 151.00 B
2018-05-02 13:28:33.147+0000 INFO [o.n.k.i.DiagnosticsManager]               write.lock: 2018-01-23T08:14:28+1100 - 0.00 B
2018-05-02 13:28:33.147+0000 INFO [o.n.k.i.DiagnosticsManager]             - Total: 2018-05-02T23:14:29+1000 - 2.00 kB
2018-05-02 13:28:33.148+0000 INFO [o.n.k.i.DiagnosticsManager]             failure-message: 2018-01-23T08:14:28+1100 - 16.00 kB
2018-05-02 13:28:33.148+0000 INFO [o.n.k.i.DiagnosticsManager]           - Total: 2018-01-23T08:14:28+1100 - 18.00 kB
2018-05-02 13:28:33.148+0000 INFO [o.n.k.i.DiagnosticsManager]           native-1.0:
2018-05-02 13:28:33.148+0000 INFO [o.n.k.i.DiagnosticsManager]             index-50: 2018-05-02T23:28:32+1000 - 40.00 kB
2018-05-02 13:28:33.148+0000 INFO [o.n.k.i.DiagnosticsManager]           - Total: 2018-01-23T08:14:28+1100 - 40.00 kB
2018-05-02 13:28:33.149+0000 INFO [o.n.k.i.DiagnosticsManager]         - Total: 2018-01-23T08:14:28+1100 - 58.00 kB
2018-05-02 13:28:33.149+0000 INFO [o.n.k.i.DiagnosticsManager]         57:
2018-05-02 13:28:33.149+0000 INFO [o.n.k.i.DiagnosticsManager]           lucene-1.0:
2018-05-02 13:28:33.149+0000 INFO [o.n.k.i.DiagnosticsManager]             1:
2018-05-02 13:28:33.149+0000 INFO [o.n.k.i.DiagnosticsManager]               _3.cfe: 2018-03-05T10:17:08+1100 - 305.00 B
2018-05-02 13:28:33.150+0000 INFO [o.n.k.i.DiagnosticsManager]               _3.cfs: 2018-03-05T10:17:08+1100 - 1.23 kB
2018-05-02 13:28:33.150+0000 INFO [o.n.k.i.DiagnosticsManager]               _3.si: 2018-03-05T10:17:08+1100 - 364.00 B
2018-05-02 13:28:33.150+0000 INFO [o.n.k.i.DiagnosticsManager]               segments_1l: 2018-05-02T23:14:29+1000 - 151.00 B
2018-05-02 13:28:33.151+0000 INFO [o.n.k.i.DiagnosticsManager]               write.lock: 2018-01-23T08:14:38+1100 - 0.00 B
2018-05-02 13:28:33.151+0000 INFO [o.n.k.i.DiagnosticsManager]             - Total: 2018-05-02T23:14:29+1000 - 2.03 kB
2018-05-02 13:28:33.151+0000 INFO [o.n.k.i.DiagnosticsManager]             failure-message: 2018-01-23T08:14:38+1100 - 16.00 kB
2018-05-02 13:28:33.151+0000 INFO [o.n.k.i.DiagnosticsManager]           - Total: 2018-01-23T08:14:38+1100 - 18.03 kB
2018-05-02 13:28:33.152+0000 INFO [o.n.k.i.DiagnosticsManager]           native-1.0:
2018-05-02 13:28:33.152+0000 INFO [o.n.k.i.DiagnosticsManager]             index-57: 2018-05-02T23:28:32+1000 - 40.00 kB
2018-05-02 13:28:33.152+0000 INFO [o.n.k.i.DiagnosticsManager]           - Total: 2018-01-23T08:14:38+1100 - 40.00 kB
2018-05-02 13:28:33.152+0000 INFO [o.n.k.i.DiagnosticsManager]         - Total: 2018-01-23T08:14:38+1100 - 58.03 kB
2018-05-02 13:28:33.153+0000 INFO [o.n.k.i.DiagnosticsManager]       - Total: 2018-01-23T08:14:38+1100 - 174.34 kB
2018-05-02 13:28:33.153+0000 INFO [o.n.k.i.DiagnosticsManager]     - Total: 2017-12-19T18:37:40+1100 - 174.34 kB
2018-05-02 13:28:33.153+0000 INFO [o.n.k.i.DiagnosticsManager]   - Total: 2017-12-19T18:37:40+1100 - 174.34 kB
2018-05-02 13:28:33.154+0000 INFO [o.n.k.i.DiagnosticsManager]   store_lock: 2017-11-28T22:13:23+1100 - 0.00 B
2018-05-02 13:28:33.154+0000 INFO [o.n.k.i.DiagnosticsManager] Storage summary: 
2018-05-02 13:28:33.154+0000 INFO [o.n.k.i.DiagnosticsManager]   Total size of store: 950.79 kB
2018-05-02 13:28:33.154+0000 INFO [o.n.k.i.DiagnosticsManager]   Total size of mapped files: 231.80 kB
2018-05-02 13:28:33.154+0000 INFO [o.n.k.i.DiagnosticsManager] --- STARTED diagnostics for KernelDiagnostics:StoreFiles END ---
2018-05-02 13:28:35.683+0000 INFO [o.n.k.i.DiagnosticsManager] --- SERVER STARTED START ---
2018-05-02 13:28:36.904+0000 INFO [o.n.k.i.DiagnosticsManager] --- SERVER STARTED END ---
2018-05-02 21:59:36.352+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1650ms.
2018-05-02 22:07:01.103+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 15941ms.
2018-05-03 00:18:17.277+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1703ms.
2018-05-03 13:31:32.406+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 19422ms.
2018-05-03 15:32:21.212+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 9222ms.
2018-05-03 20:41:59.746+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 6353ms.
2018-05-03 21:22:10.665+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 4912ms.
2018-05-03 23:44:26.184+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1667ms.
2018-05-04 08:24:20.546+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 17583ms.
2018-05-04 10:28:20.123+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1584ms.
2018-05-04 13:07:02.772+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 23747ms.
2018-05-04 15:07:19.061+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 8623ms.
2018-05-04 22:28:38.746+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 8035ms.
2018-05-05 00:52:22.106+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1636ms.
2018-05-05 02:52:25.104+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 391ms.
2018-05-06 21:32:37.521+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 22865ms.
2018-05-06 22:20:02.040+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 8788ms.
2018-05-07 00:20:48.042+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1618ms.
2018-05-07 08:41:39.365+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 24295ms.
2018-05-07 10:56:26.002+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1591ms.
2018-05-07 11:31:26.371+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 22960ms.
2018-05-07 11:31:52.022+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 4184ms.
2018-05-07 22:17:55.365+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1669ms.
2018-05-07 22:22:49.589+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 19339ms.
2018-05-08 00:13:09.319+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1638ms.
2018-05-08 09:28:24.765+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 24639ms.
2018-05-08 11:16:50.290+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1662ms.
2018-05-08 13:35:32.279+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1635ms.
2018-05-08 14:07:34.466+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 24385ms.
2018-05-08 14:09:07.600+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 9781ms.
2018-05-08 22:12:48.835+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1589ms.
2018-05-08 22:28:11.106+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 18823ms.
2018-05-09 00:16:01.797+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 1611ms.
2018-05-09 11:37:20.240+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 13514ms.
2018-05-09 12:11:27.731+0000 WARN [o.n.k.i.c.MonitorGc] GC Monitor: Application threads blocked for 6772ms.
2018-05-09 22:29:28.904+0000 INFO [o.n.k.i.f.GraphDatabaseFacadeFactory] Shutdown started
2018-05-09 22:29:28.905+0000 INFO [o.n.k.i.f.GraphDatabaseFacadeFactory] Database is now unavailable
2018-05-09 22:29:28.929+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [298]:  Starting check pointing...
2018-05-09 22:29:28.929+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [298]:  Starting store flush...
2018-05-09 22:29:28.980+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [298]:  Store flush completed
2018-05-09 22:29:28.980+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [298]:  Starting appending check point entry into the tx log...
2018-05-09 22:29:28.984+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [298]:  Appending check point entry into the tx log completed
2018-05-09 22:29:28.984+0000 INFO [o.n.k.i.t.l.c.CheckPointerImpl] Check Pointing triggered by database shutdown [298]:  Check pointing completed
2018-05-09 22:29:28.984+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [0]:  Starting log pruning.
2018-05-09 22:29:28.984+0000 INFO [o.n.k.i.t.l.p.LogPruningImpl] Log Rotation [0]:  Log pruning complete.
2018-05-09 22:29:29.007+0000 INFO [o.n.k.i.DiagnosticsManager] --- STOPPING diagnostics START ---
2018-05-09 22:29:29.007+0000 INFO [o.n.k.i.DiagnosticsManager] --- STOPPING diagnostics END ---

**Comment by lutovich** [comment]
There is only a lengthy garbage collection pause during that time. Nothing that could give us more information about this error. Unfortunately, I'm unable to reproduce it locally with any sane test. The only way I can see the same error is by running a test against a stub database which violates the protocol and sends incorrect messages back. This should never happen in real life.

Could you please share the code that submits queries and consumes the results?

**Comment by lutovich** [comment]
Hey @JavascriptMick, is this still a problem for you? Can you share the code or provide a repro app?

**Comment by lutovich** [comment]
Closing this issue now because of inactivity. Please feel free to update it if the problem persists.
