### ISSUE TITLE
Bolt V2 should always support byte arrays

### ISSUE THREAD

**Issue by DomVinyard** [neo4j/neo4j-javascript-driver#434]
using version 1.7.0, also tried 1.6.x.

```
Error: Bolt V2 should always support byte arrays
    at Packer.disableByteArrays (/Users/dom/Desktop/bitwars-api/node_modules/neo4j-driver/lib/v1/internal/packstream-v2.js:116:13)
    at InitializationObserver.onCompleted (/Users/dom/Desktop/bitwars-api/node_modules/neo4j-driver/lib/v1/internal/connection.js:559:50)
    at Connection._handleMessage (/Users/dom/Desktop/bitwars-api/node_modules/neo4j-driver/lib/v1/internal/connection.js:336:35)
    at Dechunker._this2._dechunker.onmessage (/Users/dom/Desktop/bitwars-api/node_modules/neo4j-driver/lib/v1/internal/connection.js:204:22)
    at Dechunker._onHeader (/Users/dom/Desktop/bitwars-api/node_modules/neo4j-driver/lib/v1/internal/chunking.js:254:14)
    at Dechunker.AWAITING_CHUNK (/Users/dom/Desktop/bitwars-api/node_modules/neo4j-driver/lib/v1/internal/chunking.js:207:21)
    at Dechunker.write (/Users/dom/Desktop/bitwars-api/node_modules/neo4j-driver/lib/v1/internal/chunking.js:265:28)
    at NodeChannel._this2._ch.onmessage (/Users/dom/Desktop/bitwars-api/node_modules/neo4j-driver/lib/v1/internal/connection.js:199:40)
    at TLSSocket.<anonymous> (/Users/dom/Desktop/bitwars-api/node_modules/neo4j-driver/lib/v1/internal/node/node-channel.js:331:16)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at TLSSocket.Readable.push (_stream_readable.js:211:10)
    at TLSWrap.onread (net.js:585:20)
```

**Comment by DomVinyard** [comment]
OK, so did some exploring. `packstream-v2.js` - 

```

    key: 'disableByteArrays',
    value: function disableByteArrays() {
      throw new Error('Bolt V2 should always support byte arrays'); // 116
    }
```

commenting out line 116 (throw) - everything works fine. it appears to be a false positive. what could be triggering this? Where is 'disableByteArrays' being set? Happy to explore more if somebody can point me in a direction

**Comment by zhenlineo** [comment]
Hi @DomVinyard
What server version you are using with the 1.7.0 driver? Could you give us an example code or project to reproduce the error?

Cheers,
Zhen

**Comment by zhenlineo** [comment]
Hi @DomVinyard,

We are missing information to continue on this issue. Please come back with more details for us to reproduce the error so that we can continue on this issue.

Zhen

**Comment by ryanmeador** [comment]
I am experiencing the same issue using driver 1.7.2 with Neo4j Community Edition 3.0.8 (on Heroku).  The issue went away when I downgraded the driver back to 1.1.0 (I didn't try any intermediate versions; that's just what I was using previously).  I don't have time right now to reduce my project to a reproducer, but I'm happy to collect logs or try any other troubleshooting steps you can suggest.  Thanks!

**Comment by alexcittadini** [comment]
> I am experiencing the same issue using driver 1.7.2 with Neo4j Community Edition 3.0.8 (on Heroku). The issue went away when I downgraded the driver back to 1.1.0 (I didn't try any intermediate versions; that's just what I was using previously). I don't have time right now to reduce my project to a reproducer, but I'm happy to collect logs or try any other troubleshooting steps you can suggest. Thanks!

Thanks mate, you saved me big time. I tried down grading to 1.4.0 and that didn't work, but 1.1.0 worked for me. No idea what caused it
