### ISSUE TITLE
Neo4jError: Ignored either because of an error or RESET

### ISSUE THREAD

**Issue by senica** [neo4j/neo4j-javascript-driver#452]
- Neo4j version: Enterprise 3.4.10
- Neo4j Mode: Casual cluster with 3 core 0 read-replica
- Driver version: NodeJS neo4j-driver@1.7.3
- Operating system: Nodejs on Docker Alpine Linux 4.4.0-145-generic; Database on Docker Alpine Linux v3.8

- **Steps to reproduce**
  Run Queries. Could be heavy load, but that doesn't always seem to be the case
- Expected behavior
  That queries execute rather than get rejected.
- Actual behavior
  I get connection reset errors or the query is ignored
```
{ app: 'api-prod',
4/18/2019 1:03:36 PM0|app      |   error: { Neo4jError: Ignored either because of an error or RESET
4/18/2019 1:03:36 PM0|app      |     at captureStacktrace (/home/node/app/node_modules/neo4j-driver/lib/v1/result.js:200:15)
4/18/2019 1:03:36 PM0|app      |     at new Result (/home/node/app/node_modules/neo4j-driver/lib/v1/result.js:73:19)
4/18/2019 1:03:36 PM0|app      |     at finishTransaction (/home/node/app/node_modules/neo4j-driver/lib/v1/transaction.js:328:10)
4/18/2019 1:03:36 PM0|app      |     at Object.commit (/home/node/app/node_modules/neo4j-driver/lib/v1/transaction.js:232:17)
4/18/2019 1:03:36 PM0|app      |     at Transaction.commit (/home/node/app/node_modules/neo4j-driver/lib/v1/transaction.js:136:35)
4/18/2019 1:03:36 PM0|app      |     at TransactionExecutor._handleTransactionWorkSuccess (/home/node/app/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:151:12)
4/18/2019 1:03:36 PM0|app      |     at /home/node/app/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:127:23
4/18/2019 1:03:36 PM0|app      |     at <anonymous>
4/18/2019 1:03:36 PM0|app      |     at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'N/A', name: 'Neo4jError' },
4/18/2019 1:03:36 PM0|app      |   query: 'MATCH (c:company {uuid: $cid})\n  RETURN {\n    paid_seats: c.paid_seats,\n    trial_end: c.trial_end\n  }',
4/18/2019 1:03:36 PM0|app      |   data: { cid: 'c5d1d277-3646-44b1-836b-6e40e68d17a7' },
4/18/2019 1:03:36 PM0|app      |   level: 'error',
4/18/2019 1:03:36 PM0|app      |   message: 'Datbase error on mixed transaction' }
```

If I take the log info and run the query, it runs fine by itself. I thought maybe it was related to transactions not being closed, so we took a database snapshot and moved it locally and we get errors locally as well.

There are no error logs under /var/lib/neo4j/logs on any of the docker containers. The debug.log does not contain any relevant information

For wholeness, we use a wrapper method to call our database calls to parse the results for us. Before we were using just `.run` and recently switched to `.writeTransaction` to try and solve the issue, but I think it got worse.

Here's the wrapper:
```
run: function(query, data, parse = true){
    return new Promise((resolve, reject)=>{
      let session = driver.session()
      session.writeTransaction((tx)=>{
        tx.run(query, data)
        .then((result)=>{
          let records = result.records.map((record)=>{
            return record
          });
          session.close()
          resolve(parse ? db.parse(records) : records);
        })
      }).catch((err)=>{
        logger.error('Datbase error on mixed transaction', {
          error: err,
          query: query,
          data: data
        });

        if (err.code === neo4j.error.SERVICE_UNAVAILABLE) {
          logger.error('Database Unavailable', err)
        }

        session.close()
        reject(err);
      })
    });
  },
```

Then we just `await _db.run(query, params)`

**Comment by senica** [comment]
I posted on Stackoverflow and realized that `email` is `undefined` so this is probably a bad example. I know other queries that are rejected are valid as I've done a copy and paste and ran them with no issue. I'll continue to investigate on my side. If anything, if it is a param error, perhaps a better error would be a value.

**Comment by senica** [comment]
Did a trial run on dev for 3.5.4 and it seems to have cleared up the issues. Will post back if that was the fix.

**Comment by senica** [comment]
Upgraded to 3.5.4-enterprise and errors went away.
