### ISSUE TITLE
Connection Reset with query importing from CSV

### ISSUE THREAD

**Issue by CarlosHPlata** [neo4j/neo4j-javascript-driver#524]
Hello I'm trying to execute the following query:

```
USING PERIODIC COMMIT LOAD CSV WITH HEADERS FROM 'ftp://example/T1map.csv' AS row 
WITH row 
WHERE 
    row['Element1'] IS NOT NULL 
AND row['Element2'] IS NOT NULL 
AND row['Element3'] IS NOT NULL 
AND row['Element4'] IS NOT NULL 
AND row['Element5'] IS NOT NULL 
AND row['Element6'] IS NOT NULL 
AND row['ELement7'] IS NOT NULL 
AND row['Element8'] IS NOT NULL 
AND row['Entity'] IS NOT NULL 

MERGE (importedNode:D1575653900056:TlEntityMapping {
    element1:row['Element1'],
    element2:row['Element2'],
    element3:row['Element3'],
    element4:row['Element4'],
    element5:row['Element5'],
    element6:row['Element6'],
    element7:row['ELement7'],
    element8:row['Element8'],
    entity:row['Entity']
}) 

ON CREATE SET 
    importedNode.accountingElements = toInteger(row['AccountingElements']), 
    importedNode.lineNumber = toInteger(row['LineNumber ']), 
    importedNode.object = row['Object'], 
    importedNode.ptSystemCategory = 'TlEntityMapping', 
    importedNode.ptSystemCategoryLabel = 'TlEntityMapping', 
    importedNode.ptSystemSubcategory = '', 
    importedNode.ptSystemCreatedByImportLogId = '0989291a-9f83-4283-ae7f-655122319198', 
    importedNode.ptSystemModifiedByImportLogId = [] 
    
ON MATCH SET 
    importedNode.accountingElements = toInteger(row['AccountingElements']), 
    importedNode.lineNumber = toInteger(row['LineNumber ']), 
    importedNode.object = row['Object'], 
    importedNode.ptSystemModifiedByImportLogId = importedNode.ptSystemModifiedByImportLogId+['0989291a-9f83-4283-ae7f-655122319198'], 
    importedNode.ptSystemSubcategory = '' 
    
RETURN count(importedNode) as count
```

But every time I send the query It throws me a connection reset, even when I run the query directly from the Neo4J Browser.

It throws me the following error:
```
2020-01-13 14:52:21.835+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [Neo.DatabaseError.General.UnknownError]: Connection reset, reference 59795e8d-3d01-4788-ba03-00dd09487b86. Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.ftp.impl.FtpClient.readServerResponse(Unknown Source)
	at sun.net.ftp.impl.FtpClient.readReply(Unknown Source)
	at sun.net.ftp.impl.FtpClient.completePending(Unknown Source)
	at sun.net.ftp.impl.FtpClient.issueCommand(Unknown Source)
	at sun.net.ftp.impl.FtpClient.close(Unknown Source)
	at sun.net.www.protocol.ftp.FtpURLConnection$FtpInputStream.close(Unknown Source)
	at java.io.PushbackInputStream.close(Unknown Source)
	at sun.nio.cs.StreamDecoder.implClose(Unknown Source)
	at sun.nio.cs.StreamDecoder.close(Unknown Source)
	at java.io.InputStreamReader.close(Unknown Source)
	at org.neo4j.csv.reader.WrappedCharReadable.close(WrappedCharReadable.java:73)
	at org.neo4j.csv.reader.AutoReadingSource.close(AutoReadingSource.java:94)
	at org.neo4j.csv.reader.BufferedCharSeeker.close(BufferedCharSeeker.java:392)
	at org.neo4j.cypher.internal.runtime.interpreted.CSVResource.close(CSVResources.scala:59)
	at org.neo4j.cypher.internal.runtime.ResourceManager.close(ResourceManager.scala:54)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$2.apply(CypherCurrentCompiler.scala:188)
	at org.neo4j.cypher.internal.compatibility.CypherCurrentCompiler$CypherExecutableQuery$$anonfun$execute$2.apply(CypherCurrentCompiler.scala:188)
	at org.neo4j.cypher.internal.v3_5.util.TaskCloser$$anonfun$close$1.apply(TaskCloser.scala:43)
	at org.neo4j.cypher.internal.v3_5.util.TaskCloser$$anonfun$close$1.apply(TaskCloser.scala:41)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.neo4j.cypher.internal.v3_5.util.TaskCloser.close(TaskCloser.scala:40)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.StandardInternalExecutionResult.close(StandardInternalExecutionResult.scala:95)
	at org.neo4j.cypher.internal.compatibility.v3_5.runtime.executionplan.StandardInternalExecutionResult.accept(StandardInternalExecutionResult.scala:190)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply$mcV$sp(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$accept$2.apply(ClosingExecutionResult.scala:158)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult$$anonfun$safelyAndClose$1.apply(ClosingExecutionResult.scala:171)
	at org.neo4j.cypher.exceptionHandler$runSafely$.apply(exceptionHandler.scala:89)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.safelyAndClose(ClosingExecutionResult.scala:174)
	at org.neo4j.cypher.internal.compatibility.ClosingExecutionResult.accept(ClosingExecutionResult.scala:157)
	at org.neo4j.bolt.v1.runtime.CypherAdapterStream.accept(CypherAdapterStream.java:73)
	at org.neo4j.bolt.v1.messaging.ResultHandler.onRecords(ResultHandler.java:40)
	at org.neo4j.bolt.v3.runtime.StreamingState.lambda$processStreamResultMessage$0(StreamingState.java:41)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.consumeResult(TransactionStateMachine.java:484)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:328)
	at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:128)
	at org.neo4j.bolt.v3.runtime.StreamingState.processStreamResultMessage(StreamingState.java:40)
	at org.neo4j.bolt.v3.runtime.AbstractStreamingState.processUnsafe(AbstractStreamingState.java:44)
	at org.neo4j.bolt.v3.runtime.FailSafeBoltStateMachineState.process(FailSafeBoltStateMachineState.java:48)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.nextState(BoltStateMachineV1.java:144)
	at org.neo4j.bolt.v1.runtime.BoltStateMachineV1.process(BoltStateMachineV1.java:92)
	at org.neo4j.bolt.messaging.BoltRequestMessageReader.lambda$doRead$1(BoltRequestMessageReader.java:89)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:191)
	at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:139)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:171)
	at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:154)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by zhenlineo** [comment]
Hi @kingskull619 
Can you give me more details about the Neo4j version, driver version. And also whether you are using a single Neo4j instance, or cluster etc. 

It would also be helpful if you could give some code that could help us recreate the error you are seeing.

Cheers,
Zhen

**Comment by senica** [comment]
Any resolve on this? I'm running into the same thing with a CSV load.

**Comment by technige** [comment]
Without more detail (as requested by @zhenlineo) we can't begin to diagnose what might be happening here. However, Neo4j 4.1 will introduce an opt-in keep-alive signal that allows long-running jobs to keep the connection from falling "idle", thereby guarding against over-zealous third-party network components closing connections. This may help here.

In the absence of further detail though, I'll close this issue, and it can be re-opened if required.
