### ISSUE TITLE
Upgraded to mose recent version of the driver cannot connect to my Aura instance

### ISSUE THREAD

**Issue by MuddyBootsCode** [neo4j/neo4j-javascript-driver#561]
Recently upgraded from version 1.7.6 of the neo4j driver and attempted to connect to my Aura instance. Received this error:
```
{
  "errors": [
    {
      "message": "Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1588242098789, routers=[], readers=[], writers=[]]",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "Well"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "code": "ServiceUnavailable",
          "name": "Neo4jError",
          "stacktrace": [
            "Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1588242098789, routers=[], readers=[], writers=[]]",
            "",
            "    at captureStacktrace (/Users/mbp/WebstormProjects/thelandmachine-api/node_modules/neo4j-driver/lib/result.js:263:15)",
            "    at new Result (/Users/mbp/WebstormProjects/thelandmachine-api/node_modules/neo4j-driver/lib/result.js:68:19)",
            "    at newCompletedResult (/Users/mbp/WebstormProjects/thelandmachine-api/node_modules/neo4j-driver/lib/transaction.js:449:10)",
            "    at Object.run (/Users/mbp/WebstormProjects/thelandmachine-api/node_modules/neo4j-driver/lib/transaction.js:287:14)",
            "    at Transaction.run (/Users/mbp/WebstormProjects/thelandmachine-api/node_modules/neo4j-driver/lib/transaction.js:123:32)",
            "    at /Users/mbp/WebstormProjects/thelandmachine-api/node_modules/neo4j-graphql-js/dist/index.js:156:25",
            "    at TransactionExecutor._safeExecuteTransactionWork (/Users/mbp/WebstormProjects/thelandmachine-api/node_modules/neo4j-driver/lib/internal/transaction-executor.js:134:22)",
            "    at TransactionExecutor._executeTransactionInsidePromise (/Users/mbp/WebstormProjects/thelandmachine-api/node_modules/neo4j-driver/lib/internal/transaction-executor.js:122:32)",
            "    at Timeout._onTimeout (/Users/mbp/WebstormProjects/thelandmachine-api/node_modules/neo4j-driver/lib/internal/transaction-executor.js:98:18)",
            "    at listOnTimeout (internal/timers.js:549:17)"
          ]
        }
      }
    }
  ],
  "data": {
    "Well": null
  }
}
```

If I swap back to the older version of the driver it works again.

**Comment by zhenlineo** [comment]
Hi, Neo4j 4.0 drivers by default have encryption turned off. If your server requires encryption, then your driver will not be able to connect. Could you check if your server and driver security settings are compatiable?

**Comment by zhenlineo** [comment]
When connecting Aura, the server by default has encryption on. Checkout [this](https://neo4j.com/docs/driver-manual/4.0/client-applications/#driver-connection-uris) for more details

**Comment by MuddyBootsCode** [comment]
Thanks: I ended up going with this and it worked:
```
const driver = neo4j.driver(uri, neo4j.auth.basic(user, password), {
  encrypted: 'ENCRYPTION_ON',
  trust: 'TRUST_ALL_CERTIFICATES'
})
```
