### ISSUE TITLE
npm test fail

### ISSUE THREAD

**Issue by whatSocks** [neo4j/neo4j-javascript-driver#59]
I'm running 3.0.0-RC1 on localhost on a mac
node v5.10.1 / npm 3.8.3 (latest stable from nvm)

```
➜  neo4j-javascript-driver git:(1.1) npm test

> neo4j-driver@1.1.0-dev test /Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver
> gulp test

[11:30:50] Using gulpfile ~/Documents/_projects/TSL/neo4j-javascript-driver/gulpfile.js
[11:30:50] Starting 'test'...
[11:30:50] Starting 'nodejs'...
[11:30:53] Finished 'nodejs' after 2.5 s
[11:30:53] Starting 'test-nodejs'...
.............................F....................................................................................

Failures:
1) trust-signed-certificates should accept known certificates
1.1) Error: ENOENT: no such file or directory, open 'build/neo4j-enterprise-3.1.0/certificates/neo4j.cert'
    Error: ENOENT: no such file or directory, open 'build/neo4j-enterprise-3.1.0/certificates/neo4j.cert'
        at Error (native)
        at Object.fs.openSync (fs.js:584:18)
        at fs.readFileSync (fs.js:431:33)
        at Array.map (native)
        at Object.TRUST_SIGNED_CERTIFICATES (/Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver/lib/v1/internal/ch-node.js:97:36)
        at connect (/Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver/lib/v1/internal/ch-node.js:161:37)
        at new NodeChannel (/Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver/lib/v1/internal/ch-node.js:194:18)
        at connect (/Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver/lib/v1/internal/connector.js:474:25)
        at Driver._createConnection (/Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver/lib/v1/driver.js:101:49)
        at Pool.acquire (/Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver/lib/v1/internal/pool.js:69:21)

114 specs, 1 failure
Finished in 4.6 seconds
[11:30:58] 'test-nodejs' errored after 4.71 s
[11:30:58] Error in plugin 'gulp-jasmine'
Message:
    Tests failed
[11:30:58] 'test' errored after 7.21 s
[11:30:58] Error in plugin 'run-sequence'
Message:
    An error occured in task 'test-nodejs'.
npm ERR! Test failed.  See above for more details.
```

tried again with `./runTests.sh`

```
➜  neo4j-javascript-driver git:(1.1) ✗ ./runTests.sh

> neo4j-driver@1.1.0-dev start-neo4j /Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver
> gulp start-neo4j

[11:32:46] Using gulpfile ~/Documents/_projects/TSL/neo4j-javascript-driver/gulpfile.js
[11:32:46] Starting 'download-neo4j'...
[gulp] Downloading http://alpha.neohq.net/dist/neo4j-enterprise-3.1.0-NIGHTLY-unix.tar.gz... undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% undefined% Done
[11:33:49] Finished 'download-neo4j' after 1.05 min
[11:33:49] Starting 'set-password'...
[11:33:50] Finished 'set-password' after 139 ms
[11:33:50] Starting 'start-neo4j'...
Starting Neo4j.
Started neo4j (pid 58248). By default, it is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver/build/neo4j-enterprise-3.1.0/logs/neo4j.log for current status.
[11:33:50] Finished 'start-neo4j' after 556 ms

> neo4j-driver@1.1.0-dev test /Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver
> gulp test

[11:33:54] Using gulpfile ~/Documents/_projects/TSL/neo4j-javascript-driver/gulpfile.js
[11:33:54] Starting 'test'...
[11:33:54] Starting 'nodejs'...
[11:33:56] Finished 'nodejs' after 2.49 s
[11:33:56] Starting 'test-nodejs'...
.............................F...............................................F....................................

Failures:
1) trust-signed-certificates should accept known certificates
1.1) Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timeout._onTimeout (/Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1909:23)
        at tryOnTimeout (timers.js:224:11)
        at Timer.listOnTimeout (timers.js:198:5)

2) transaction should handle failures with subscribe
2.1) Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timeout._onTimeout (/Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1909:23)
        at tryOnTimeout (timers.js:224:11)
        at Timer.listOnTimeout (timers.js:198:5)

114 specs, 2 failures
Finished in 18 seconds
[11:34:15] 'test-nodejs' errored after 18 s
[11:34:15] Error in plugin 'gulp-jasmine'
Message:
    Tests failed
[11:34:15] 'test' errored after 21 s
[11:34:15] Error in plugin 'run-sequence'
Message:
    An error occured in task 'test-nodejs'.
npm ERR! Test failed.  See above for more details.

> neo4j-driver@1.1.0-dev stop-neo4j /Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver
> gulp stop-neo4j

[11:34:18] Using gulpfile ~/Documents/_projects/TSL/neo4j-javascript-driver/gulpfile.js
[11:34:18] Starting 'stop-neo4j'...
Neo4j not running
[11:34:18] Finished 'stop-neo4j' after 290 ms
```

**Comment by whatSocks** [comment]
woops, I realized I forgot to run `npm build` before running the tests. I did that and got just one error:

```
.............................F....................................................................................

Failures:
1) trust-signed-certificates should accept known certificates
1.1) Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timeout._onTimeout (/Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1909:23)
        at tryOnTimeout (timers.js:224:11)
        at Timer.listOnTimeout (timers.js:198:5)

114 specs, 1 failure
Finished in 8.9 seconds
[11:42:38] 'test-nodejs' errored after 8.97 s
[11:42:38] Error in plugin 'gulp-jasmine'
Message:
    Tests failed
[11:42:38] 'test' errored after 12 s
[11:42:38] Error in plugin 'run-sequence'
Message:
    An error occured in task 'test-nodejs'.
npm ERR! Test failed.  See above for more details.

> neo4j-driver@1.1.0-dev stop-neo4j /Users/cristina/Documents/_projects/TSL/neo4j-javascript-driver
> gulp stop-neo4j

[11:42:40] Using gulpfile ~/Documents/_projects/TSL/neo4j-javascript-driver/gulpfile.js
[11:42:40] Starting 'stop-neo4j'...
Neo4j not running
[11:42:40] Finished 'stop-neo4j' after 303 ms
```

**Comment by gurkerl83** [comment]
Hi,
don't know whats going on, do you have a second neo4j database running? We saw the same test results as we had accidentally started the standalone neo4j (version 3.0.0-RC1) and initiated the gulp test. Further, we run into some problems with the transport channel selection process solved in a custom fork available at https://github.com/gurkerl83/neo4j-javascript-driver.

my setup is - node: 5.3.0 - npm: 3.8.6

Thanks,

**Comment by whatSocks** [comment]
oops, works now, thanks :D

**Comment by whatSocks** [comment]
this was also the reason why none of the example code was working for me

**Comment by pontusmelke** [comment]
Ok, great that you were able to figure it out, I'll close this issue please reopen or open a new one if you have any troubles.
