### ISSUE TITLE
ServiceUnavailable when a 30 queries are sent at the same time

### ISSUE THREAD

**Issue by Nikoms** [neo4j/neo4j-javascript-driver#593]
Hello!

I have a strange problem with my connection to neo4j. I have an api call that calls a lot our database (something like 30 queries at the same time)... And "Sometimes" (really random), some of them fail. If i use the "read transaction" function. It works (after 30 sec), if I use the "auto commit run" function, it fails after 30 sec. We use the last version of the driver and our database is in another datacenter (Api in Paris -> DB in Frankfurt). I see that when our API is in the same datacenter (Api in Frankfurt -> DB in Frankfurt) it seems to work without problem

**Neo4j Version:** Neo4j Community Edition 3.5.17
**Neo4j Mode**: Single instance  
**Driver version**: JS driver 4  

### Steps to reproduce

That's the problem, It's random on the Paris server :(

### Expected behavior

As there is only 30 queries in parrallel, I suppose we shouldn't have a timeout

### Actual behavior
Here are some logs:

``` 
2020-06-30T14:25:19+02:00 Neo4j (debug) Connection [23][] closed
2020-06-30T14:25:19+02:00 Neo4j (error) Connection [23][] experienced a fatal error {"code":"ServiceUnavailable","name":"Neo4jError"}
2020-06-30T14:25:19+02:00 "error": "Neo4jError: Failed to connect to server. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0. Caused by: Failed to establish connection in 30000ms",
2020-06-30T14:25:19+02:00 "errorObject": {
2020-06-30T14:25:19+02:00 "code": "ServiceUnavailable",
2020-06-30T14:25:19+02:00 "name": "Neo4jError"
2020-06-30T14:25:19+02:00 at resolveFieldValueOrError (/home/bas/app_29e858ed-6c3d-4fbb-895c-cdc498bf039f/node_modules/graphql/execution/execute.js:531:18)
2020-06-30T14:25:19+02:00 at Array.reduce (<anonymous>)
2020-06-30T14:25:19+02:00 at executeFields (/home/bas/app_29e858ed-6c3d-4fbb-895c-cdc498bf039f/node_modules/graphql/execution/execute.js:361:42)
2020-06-30T14:25:19+02:00 at collectAndExecuteSubfields (/home/bas/app_29e858ed-6c3d-4fbb-895c-cdc498bf039f/node_modules/graphql/execution/execute.js:772:10)
2020-06-30T14:25:19+02:00 at completeObjectValue (/home/bas/app_29e858ed-6c3d-4fbb-895c-cdc498bf039f/node_modules/graphql/execution/execute.js:762:10)
2020-06-30T14:25:19+02:00 at completeValue (/home/bas/app_29e858ed-6c3d-4fbb-895c-cdc498bf039f/node_modules/graphql/execution/execute.js:660:12) {
2020-06-30T14:25:19+02:00 code: 'ServiceUnavailable'
2020-06-30T14:25:19+02:00 }
2020-06-30T14:25:19+02:00 }
2020-06-30T14:25:19+02:00 }
2020-06-30T14:25:19+02:00 @app/database executeQueryError: An error has occured during the Cypher query execution.
2020-06-30T14:25:19+02:00 Neo4j (debug) Connection [23][] closing 

```

Another strange thing is that it closes the connection "23", but I don't see any opening connection in the logs :( I suppose that the last "closing" line is displayed because we "close" the connection manually in the "finally"

**Comment by technige** [comment]
From the description of your problem, specifically with your remote data centre, this is more than likely a networking issue at your end. Indeed, I would also say that the retry mechanism built into `readTransaction` is working as expected; auto-commit transactions do not provide a similar retry facility. So given the apparent intermittent connectivity issues you see, I would recommend only using transaction functions for all your database interaction.
