### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by xeroxstar** [neo4j/neo4j-javascript-driver#693]
- Neo4j version: 4.2.1 CE (Neo4j Desktop 1.4.3)
- Driver Version: 4.2.3
- Operating System: Windows 10 Pro
- Nodejs Version v12.13.0

I am trying to setup the driver but getting an error:
`const neo4j = require('neo4j-driver')`

```
Error: Cannot find module 'C:\Users\x\Desktop\projects\app\node_modules\rxjs\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:294:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:525:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:781:27)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\x\Desktop\projects\app\node_modules\neo4j-driver\lib\session-rx.js:14:13)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\x\\Desktop\\projects\\app\\node_modules\\rxjs\\package.json',
  requestPath: 'rxjs'
}
```

**Comment by xeroxstar** [comment]
I guess the `rxjs` package version(`6.6.3`) was already been installed but not working with neo4j so i fixed it by running npm install` rxjs@6.6.6` (latest version)
